name: serial
description: Serial port for flutter. Wrapper around the `window.navigator.serial` for web platform.
version: 0.0.5
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_serial/

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  js: ^0.7.1

dev_dependencies:
  test: ^1.25.8
  lints: ^5.0.0
